### ISSUE TITLE
Breaking API change

### ISSUE THREAD

**Issue by jasonmit** [shinnn/broccoli-clean-css#14]
It appears between 1.0.0 and 1.1.0 the `options.strict`, which would throw if there was an error and `strict` was truthy (false by default), was removed:
https://github.com/shinnn/broccoli-clean-css/blob/v1.0.0/index.js#L42-L44

This results in builds failing since they started pulling in newer versions of the lib, see: https://github.com/ember-cli/ember-cli-preprocessor-registry/issues/8

Would you be willing to accept a PR to bring it back for 1.x and in 2.x revisit removing it to respect semver?

Thanks, and great plugin :+1:

**Comment by shinnn** [comment]
@jasonmit Thanks for this report, and sorry for my late, really late response (over 1 year!).

I had thought of the best way to fix https://github.com/ember-cli/ember-cli-preprocessor-registry/issues/8  for a long time.

1. As you said, broccoli-clean-css v1.1.0 includes a breaking change and I should add `strict` option again and publish v1.1.1.

2. Basically, I should have not add `strict` option to this plugin. It does not solve any problems, but in fact it dangerously hides errors that the CSS authors would rather fix. Even if I revert `strict` option removal, https://github.com/ember-cli/ember-cli-preprocessor-registry/issues/8 is not actually solved. What they really should do is not pretending that they didn't see the error, but editing their CSS file and fix broken `@import`.

I've struggled with those two my own conflicting opinion, and here is my final conclusion:

1. Publish broccoli-clean-css v2.0.0 *without `strict` option*.
2. Hazardous `strict` option will never been restored in v1.x. If you want to swallow the error at any cost, use clean-css [`inline`](https://github.com/jakubpawlowicz/clean-css#inlining-options) option instead. Otherwise, though I think this is the worst solution, pin [the version of `broccoli-clean-css` in package.json](https://github.com/ember-cli/ember-cli-preprocessor-registry/blob/17060ce1d1df9aa079118fe0ff0c9805262a8de1/package.json#L25) to `1.0.0`.

So, https://github.com/ember-cli/ember-cli-preprocessor-registry/issues/8 won't be fixed by my side.

Thanks.
