### ISSUE TITLE
Minification 'breaking' certain sass files?

### ISSUE THREAD

**Issue by brendanoh** [shinnn/broccoli-clean-css#6]
I am not sure if this is an issue in this repo or Ember-CLI. I am using Ember-CLI and local css works fine but prod is broken when css is minified. My app.scss file below:

```
div.md {
  @import "components/materializecss";
}

div.found {
  @import "foundation";
}
```

This nesting allows separate areas of the app to be exclusively MD or Found styles. However, after minification none of the styles work correctly.

**Comment by steffenbrem** [comment]
I have the same issue.

**Comment by brendanoh** [comment]
I could only solve by not minifying @steffenbrem 

No changes made to this repo for 90 days so I dont think anyone will reply.

**Comment by shinnn** [comment]
Is it really a plugin-specific problem? Seems an issue with [clean-css](https://github.com/jakubpawlowicz/clean-css) itself.

**Comment by shinnn** [comment]
> after minification none of the styles work correctly.

@brendanoh Can you elaborate on "work correctly"?

**Comment by shinnn** [comment]
Closing this since:

1. The current latest ember-cli on npm (v1.13.8) still uses an older version of broccoli-clean-css, so maybe it's already fixed in the latest version.

  ```
  $ npm view ember-cli@1.13.8 dependencies.broccoli-clean-css
  > 0.2.0
  ```
2. After the next release, ember-cli won't use broccoli-clean-css. https://github.com/ember-cli/ember-cli/commit/489f68b6a3bdca1bb4aadefb71c5ba75a6b22bbc#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L78

**Comment by shinnn** [comment]
Thanks for reporting though.
